src/main/java/org/mule/extension/http/internal/request/HttpRequesterProvider.java, src/main/java/org/mule/extension/http/internal/request/RequestConnectionParams.java
DO NOT MERGE: Cannot verify tests until they are fixed.
=> MULE-12585: Allow HTTP streaming to be turned off

src/main/java/org/mule/extension/http/internal/listener/HttpListener.java, src/test/java/org/mule/test/http/BasicHttpTestCase.java, src/test/resources/basic-http-config.xml
=> MULE-12448: Sources error handling is inconsistent

src/main/java/org/mule/extension/http/internal/listener/HttpListener.java
=> MULE-12673: fix cases when an exception occurs in an error handler

src/main/java/org/mule/extension/http/internal/listener/HttpListener.java
=> MULE-12832: Avoid generating stacktraces for exceptions when verbose is

src/main/java/org/mule/extension/http/internal/filter/BasicUnauthorisedException.java
=> MULE-13045 - Avoid passing the FlowConstruct around just to get the name

src/test/java/org/mule/test/http/functional/proxy/HttpProxyTemplateTestCase.java, src/test/resources/http-proxy-template-config.xml, src/test/resources/sensing-request-response-processor-bean.xml
=> MULE-13007: Every exported Mule package must contain api (part3)

src/test/java/org/mule/test/http/functional/listener/HttpListenerLifecycleTestCase.java, src/test/resources/http-listener-lifecycle-config.xml
=> MULE-13258: Every exported Mule package must contain api (part5)

src/test/java/org/mule/test/http/functional/listener/HttpListenerNotificationsTestCase.java, src/test/java/org/mule/test/http/functional/requester/HttpRequestNotificationsTestCase.java
_ Cleaning mule context builder
=> MULE-13433: Every exported Mule package must contain api (part6)

src/test/java/org/mule/test/http/functional/requester/HttpRequestInboundPartsTestCase.java, src/test/resources/http-request-inbound-attachments-config.xml, src/test/resources/http-request-outbound-parts-config.xml
This changes require a DW fix.
=> MULE-13401: Adapt multipart test once DW bugs are fixed

src/main/java/org/mule/extension/http/internal/HttpMetadataKey.java, src/main/java/org/mule/extension/http/internal/HttpMetadataResolver.java, src/main/java/org/mule/extension/http/internal/listener/HttpListener.java, src/main/java/org/mule/extension/http/internal/request/HttpRequestOperations.java
Reverts mulesoft/mule-http-connector#129
=> Revert "MULE-13435: DataSense medatadata fails when the application is runnin…"

src/main/java/org/mule/extension/http/api/listener/HttpBasicAuthenticationFilter.java
=> MULE-13814: Remove org.apache.logging.log4j:log4j-slf4j-impl from

src/test/resources/http-listener-overload-config.xml
=> MULE-13863: Notifications fail in test:processor when flow executions

src/main/java/org/mule/extension/http/internal/listener/HttpRequestAttributesBuilder.java
=> MULE-13973: Improve header handling performance in

pom.xml
This reverts commit befac85d9e9644d72bb9e3cd771d461bd794ab53.
=> Revert "Update MuleCoreModulesParent in pom to version 1.0.0 (#162)"

src/main/java/org/mule/extension/http/internal/listener/HttpRequestAttributesResolver.java, src/test/java/org/mule/test/http/functional/requester/HttpRequestMultipleValueHeadersTestCase.java
=> MULE-14519: HTTP: Performance improvements in requester

pom.xml, src/main/java/org/mule/extension/http/api/request/authentication/HttpRequestAuthentication.java, src/main/java/org/mule/extension/http/internal/request/HttpRequester.java
=> MULE-11272: Support non-blocking for HTTP authentication retry

src/test/java/org/mule/test/http/api/HttpRequestAttributesTestCase.java, src/test/java/org/mule/test/http/api/HttpResponseAttributesTestCase.java, src/test/java/org/mule/test/http/api/policy/HttpPolicyRequestAttributesTestCase.java, src/test/java/org/mule/test/http/api/policy/HttpPolicyResponseAttributesTestCase.java, src/test/java/org/mule/test/http/functional/listener/HttpListenerHttpMessagePropertiesTestCase.java
- Fixing failing tests in Windows due to differences between OS line breaks.
- Fixing tests with local address issue.
=> MULE-15685: Fix HTTP connector tests in Windows

pom.xml, src/main/java/org/mule/extension/http/internal/request/HttpRequester.java, src/main/java/org/mule/extension/http/internal/request/HttpResponseToResult.java
* Remove unnecessary reactor overhead in response handling
=> MULE-15924: Miscellaneous performance improvements for proxy scenario

src/main/java/org/mule/extension/http/api/request/builder/QueryParam.java, src/main/java/org/mule/extension/http/api/request/builder/RequestHeader.java, src/main/java/org/mule/extension/http/api/request/validator/RangeStatusCodeValidator.java, src/test/java/org/mule/test/http/functional/requester/DynamicHttpRequestConfigTestCase.java, src/test/resources/http-dynamic-requester-config.xml
=>  MULE-16652: HTTP Connector does not implement equals/hash on RequestHeader POJO

src/main/java/org/mule/extension/http/internal/listener/HttpListenerResponseSender.java
=> MULE-17693: onErrorSendingResponse public method in anonymous class is not accessible via reflection

pom.xml, src/main/java/org/mule/extension/http/api/HttpRequestAttributes.java, src/main/java/org/mule/extension/http/api/HttpRequestAttributesBuilder.java, src/main/java/org/mule/extension/http/api/HttpResponseAttributes.java, src/test/munit/attributes/attributes-created-dw-test-case.xml
* Also, add support for MTF tests
=> MULE-17848: Add builder methods for http attribute classes

src/main/java/org/mule/extension/http/internal/listener/HttpListener.java
=> MULE-17924: Optimize error handling performance

src/main/java/org/mule/extension/http/api/policy/HttpListenerPolicyPointcutParametersFactory.java, src/test/java/org/mule/test/http/policy/HttpListenerPolicyPointcutParametersFactoryTestCase.java
requires 
https://github.com/mulesoft/mule/pull/8631
=> MULE-18030: Fix method name typo

src/main/java/org/mule/extension/http/api/listener/HttpBasicAuthenticationFilter.java, src/test/java/org/mule/test/http/api/HttpListenerAuthenticationHandlerTestCase.java
=> MULE-18039: Improve performance of

src/main/java/org/mule/extension/http/internal/listener/HttpListenerResponseSender.java, src/main/java/org/mule/extension/http/internal/listener/HttpResponseFactory.java
EE-7205: General HTTP improvements
=> EE-7205: General HTTP improvements (#399)

src/main/java/org/mule/extension/http/api/policy/HttpListenerPolicyPointcutParametersFactory.java, src/test/java/org/mule/test/http/policy/HttpListenerPolicyPointcutParametersFactoryTestCase.java
related PRs
mule:
- https://github.com/mulesoft/mule-policy-api/pull/33
- https://github.com/mulesoft/mule-http-policy-api/pull/32
- https://github.com/mulesoft/mule/pull/8643
- https://github.com/mulesoft/mule-http-connector/pull/417
- https://github.com/mulesoft/mule-ee/pull/3352
gateway:
- https://github.com/mulesoft/api-gateway-api/pull/84
- https://github.com/mulesoft/api-gateway/pull/1106
=> MULE-18030: Provide only required headers for policy matching

src/main/resources/META-INF/org/mule/runtime/core/config/registry-bootstrap.properties
=> MULE-18108: Expose maskedPath as pointcut parameter in HTTP 1.x

pom.xml, src/main/java/org/mule/extension/http/internal/listener/HttpListenerProvider.java, src/test/java/org/mule/test/PipedStreamGenerator.java, src/test/java/org/mule/test/http/functional/HttpStreamingTestCase.java, src/test/munit/response-streaming/selectors-not-being-blocked-when-response-streaming.xml
(cherry picked from commit eb590ca71bad70859b93815a3f1bde0071effe28)
=> MULE-18028: Use IO threads to handle HTTP response streaming (#410)

src/main/java/org/mule/extension/http/api/request/authentication/HttpRequestAuthentication.java, src/main/java/org/mule/extension/http/internal/request/HttpRequestOperations.java, src/main/java/org/mule/extension/http/internal/request/HttpRequester.java, src/main/java/org/mule/extension/http/internal/request/HttpResponseToResult.java, src/test/java/org/mule/extension/http/internal/request/HttpRequesterAuthConsumesPayloadTestCase.java, src/test/java/org/mule/extension/http/internal/request/HttpResponseToResultTestCase.java
(cherry picked from commit 83f45923eb74c50f18b544cabf3508e958a6d57e)
=> MULE-18307: Using "payload" in an expression for refreshTokenWhen property results in an Error (#469)

src/main/java/org/mule/extension/http/internal/request/HttpRequesterConnectionManager.java, src/main/java/org/mule/extension/http/internal/request/HttpRequesterProvider.java, src/test/java/org/mule/test/http/AllureConstants.java, src/test/java/org/mule/test/http/functional/requester/HttpRequestConfigTestCase.java
(cherry picked from commit 26aa7a2c603ee5c0080c30a73c13feee734234ba)
=> MULE-18757: HTTP request conf doesn't updated after redeploy when app is associated with a domain

src/main/java/org/mule/extension/http/api/listener/HttpBasicAuthenticationFilter.java, src/test/java/org/mule/test/http/api/HttpListenerAuthenticationHandlerTestCase.java
* Changing encoding to UTF-8
* Removing unused import
(cherry picked from commit 9b1e6f5266f16bc7aa1d44250981a6f5d9affa3e)
=> HTTPC-137: Change authentication token decoding to UTF-8 (#497)

pom.xml
Co-authored-by: Engineering Services Bot <engineering-services-bot@mulesoft.com>
(cherry picked from commit 1597d76100281840857b9fa2537bf527d789b013)
=> Update dependency org.mule.connectors:mule-sockets-connector to v1.2.1

src/main/java/org/mule/extension/http/internal/request/HttpResponseToResult.java, src/test/java/org/mule/extension/http/internal/request/HttpResponseToResultTestCase.java
Reverts mulesoft/mule-http-connector#515
Reverting because of wrong commit name
=> Revert "HTTPC-141: Reduce memory consumption when parsing Media Type"

src/main/java/org/mule/extension/http/internal/request/HttpResponseToResult.java, src/test/java/org/mule/extension/http/internal/request/HttpResponseToResultTestCase.java
(cherry picked from commit f49a332b018091c98458ac4f3394cc5370dafd21)
=> HTTPC-141: Reduce memory consumption when parsing Media Type (#518)

src/test/munit/redirect/redirect-test-case.xml
* MULE-19622: add munit redirect tests
(cherry picked from commit ef26b654d84955bdd6519c5876e1f2bd176620ac)
=> MULE-19622: add munit redirect tests (#523)

src/test/munit/redirect/parallel-redirect-test-case.xml
(cherry picked from commit 27cc87074eb3b65290e652e13aa8ea86ab318298)
=> MULE-19622: fix broken test

src/test/munit/redirect/parallel-redirect-test-case.xml
* Parallel redirects test case
(cherry picked from commit a4c57a0592c76540577c7a85c4e5686340f5b814)
=> MULE-19622: Parallel redirects test case (#525)

src/test/munit/redirect/parallel-redirect-test-case.xml, src/test/munit/redirect/redirect-test-case.xml
(cherry picked from commit 984ee496afb3e15a25969544669086bd9633fd15)
=> MULE-19908: test query params in redirect URI (#551)

src/main/java/org/mule/extension/http/api/HttpMessageBuilder.java, src/main/java/org/mule/extension/http/api/request/builder/HttpRequesterRequestBuilder.java, src/main/java/org/mule/extension/http/internal/request/HttpRequestOperations.java, src/main/java/org/mule/extension/http/internal/request/UriUtils.java
(cherry picked from commit f2fb6eb406e64a8388e877e61316e680e264f998)
=> HTTPC-173: Extract URI methods to a utility class (#564)

src/main/java/org/mule/extension/http/api/request/builder/HttpRequestBuilderConfigurer.java, src/main/java/org/mule/extension/http/api/request/builder/HttpRequesterRequestBuilder.java, src/main/java/org/mule/extension/http/api/request/builder/HttpRequesterSimpleRequestBuilder.java, src/main/java/org/mule/extension/http/api/request/builder/HttpRequesterTestRequestBuilder.java, src/main/java/org/mule/extension/http/internal/request/HttpPollingSource.java, src/main/java/org/mule/extension/http/internal/request/HttpRequestFactory.java, src/main/java/org/mule/extension/http/internal/request/HttpRequester.java, src/main/java/org/mule/extension/http/internal/request/HttpRequesterConfig.java, src/test/java/org/mule/test/http/AllureConstants.java, src/test/java/org/mule/test/http/functional/requester/HttpRequestAuthTestCase.java, src/test/java/org/mule/test/http/functional/requester/HttpRequestAuthUtils.java, src/test/java/org/mule/test/http/functional/requester/HttpRequestPollingSourceAuthTestCase.java, src/test/munit/polling-source/http-polling-failing-connection.xml, src/test/munit/polling-source/http-polling-source-basic.xml, src/test/munit/polling-source/http-polling-timeout.xml, src/test/munit/polling-source/https-polling-source.xml, src/test/resources/http-polling-auth.xml
This is the first of a series of PRs. This doesn't include watermarking, splitting, idempotency, or response validations. 
Those are tracked in different tasks
=> HTTPC-160: Create an HTTP polling source

src/main/java/org/mule/extension/http/api/request/HttpConnectivityValidator.java
Added new method HttpConnectivityValidator for use by composer http wrapper.
=> [w-10660947] composer connectivity testing

pom.xml
(cherry picked from commit 7296b68c1e50a294588968f6b4b1d549e2b2a57f)
=> W-11929500: Remove commons-text dependency and add commons-lang3 dependency. (#641) (#643)

src/main/java/org/mule/extension/http/internal/request/HttpRequestFactory.java
(cherry picked from commit 794b887fa4765f7453c9cd151430454442117969)
=> W-11889659: Remove body from warn message (#656)

src/main/java/org/mule/extension/http/internal/listener/ListenerPath.java, src/test/java/org/mule/extension/http/internal/listener/ListenerPathTestCase.java
(cherry picked from commit fbc99d6bc23dd1753b7cc200012c53c35776cedd)
=> W-11992337: Fix relative path resolution in ListenerPath (#657)

pom.xml
(cherry picked from commit dc72b8b88ea3fcbd48a5f75e6c31253f3bf7e87e)
=> W-12150785: Remove runtimeVersion from HTTP Connector pom.xml (#659)

src/main/java/org/mule/extension/http/internal/request/HttpClientReflection.java, src/main/java/org/mule/extension/http/internal/request/HttpRequester.java, src/main/java/org/mule/extension/http/internal/request/HttpRequesterConnectionManager.java, src/main/java/org/mule/extension/http/internal/request/client/HttpExtensionClient.java, src/test/java/org/mule/extension/http/internal/request/HttpRequesterAuthConsumesPayloadTestCase.java, src/test/munit/redirect/redirect-test-case.xml
(cherry picked from commit 9a9e1e38aeb5da9b3c14b77495a443a25b5fc902)
=> W-12594415: HTTP Connector POST 303 Redirect passing body into the GET Request (#693)

src/test/munit/redirect/redirect-test-case.xml
(cherry picked from commit 9189b9d784326898e9bb7094d13460263cfe1c47)
=> W-12594415: HTTP Connector POST 303 Redirect passing body into the GET Request (#697)

pom.xml, src/test/java/org/mule/extension/http/internal/request/HttpRequesterAuthConsumesPayloadTestCase.java
(cherry picked from commit f9a6140168ba17700d44e99093043549f39cdd5b)
=> W-13564979: Fix HTTP Connector build (#700)

pom.xml
=> W-14149148: Mark http-connector as supporting java 17

pom.xml
(cherry picked from commit eee4d3e7b2ba64f8c5ebb927027a7690830fbfb1)
=> Update spring from version 5.3.18 to 5.3.30. (#746)

mule-http-connector/src/main/java/org/mule/extension/http/internal/listener/HttpListenerProvider.java
(cherry picked from commit 493e2b58a31a12b08f1a2712ddd9edfdb22647fd)
=> W-14729455: Remove old WA which is causing an illegal access in JDK17 (#784)

build.yaml, mule-http-connector/pom.xml
(cherry picked from commit 5e813054d3580983cc73c34d2f643342642e3ddd)
=> W-14729498: Update MUnit version (#783)

functional-tests/pom.xml
(cherry picked from commit 5ef1162ae426dfb8f5aed5899f892d290764dca6)
=> W-15058738: Add formatter in functional tests (#801)

mule-http-connector/pom.xml
(cherry picked from commit b8a4a7a312bf6ee8f0326c1afda3542bcd8aab23)
=> W-15195048: Update springframework dependency to 5.3.32 (#810)

.github/CODEOWNERS
=> W-15243544 Update CODEOWNERS

functional-tests/http/src/test/java/org/mule/test/http/functional/listener/HttpListenerConfigFunctionalTestCase.java, functional-tests/http/src/test/java/org/mule/test/http/functional/listener/HttpListenerTlsInsecureTestCase.java, functional-tests/http/src/test/java/org/mule/test/http/functional/requester/HttpRequestErrorHandlingTestCase.java, functional-tests/http/src/test/java/org/mule/test/http/functional/requester/HttpRequestMaxConnectionsTestCase.java
Some of the tests were accordingly modified to support change of messages or other small stuff that started happening with Netty
=> W-15400264: Modify some tests to handle new slight behaviour changes of Netty

mule-http-connector/src/main/java/org/mule/extension/http/internal/listener/HttpListener.java
(cherry picked from commit e728b602fb097d1d70e4db20f62a93879495f466)
=> W-15809219: Fix an NPE when the HTTP Listener is stopped after a failed start (#742)

functional-tests/cors/pom.xml, functional-tests/pom.xml
(cherry picked from commit 1bd68076625a28a07d17120833765b96d9487edd)
=> W-15874250: Update mule dependency to 4.8.0-SNAPSHOT in HTTP functional tests (#842)

functional-tests/http/src/test/java/org/mule/test/http/functional/listener/crl/HttpListenerCrlNoRevocationTestCase.java, functional-tests/http/src/test/java/org/mule/test/http/functional/listener/crl/HttpListenerCrlRevocationTestCase.java, functional-tests/http/src/test/java/org/mule/test/http/functional/listener/crl/HttpListenerRevocationOutdatedCrlTestCase.java, functional-tests/http/src/test/java/org/mule/test/http/functional/requester/crl/HttpPreferringCrlTestCase.java, functional-tests/http/src/test/java/org/mule/test/http/functional/requester/crl/HttpRequesterClrRevocationOutdatedCrlTestCase.java, functional-tests/http/src/test/java/org/mule/test/http/functional/requester/crl/HttpRequesterClrRevocationTestCase.java, functional-tests/http/src/test/java/org/mule/test/http/functional/requester/ocsp/HttpRequesterOcspRevocationTestCase.java
(cherry picked from commit 3c783eb674c1421f166d48e4ccdf8ad48e4c22ad)
=> W-15255505: Enabling TLS crl tests in HTTP Connector (#844)

mule-http-connector/pom.xml
* Upgrade spring version as well
=> W-17006456: Move spring dependencies in http connector to the dependency management

functional-tests/cors/pom.xml, functional-tests/http/pom.xml, functional-tests/pom.xml, mule-http-connector/pom.xml
(cherry picked from commit 0805accf2feec6ac1784899734537b82ad14d6bf)
=> W-17024176: Update Sockets Connector version to 1.2.5 (#933)

mule-http-connector/pom.xml, mule-http-connector/src/main/java/org/mule/extension/http/internal/StaticResourceLoader.java
This reverts commit 63d64a129d94bead4ed06a9d9698429de5588e0d.
=> Revert "W-16678830: Update jakarta dependencies in soap-service and http-service (#955)"

mule-http-connector/pom.xml, mule-http-connector/src/main/java/org/mule/extension/http/internal/StaticResourceLoader.java
This reverts commit 869b5a7faa515474b68b01f97e176cba3282687c.
=> Revert "W-17281517: Upgrade jakarta dependencies (#957)"
