src/test/java/org/mule/test/http/functional/listener/HttpListenerConfigFunctionalTestCase.java
src/test/java/org/mule/test/http/utils/SocketRequester.java

Adding functional test case to verify special characters are escaped.

MULE-13034: Error responses with special characters should be escaped.

---

pom.xml
src/test/java/org/mule/test/http/functional/listener/HttpListenerValidateCertificateTestCase.java
src/test/java/org/mule/test/http/functional/requester/HttpRequestErrorHandlingTestCase.java
src/test/java/org/mule/test/http/functional/requester/HttpRequestFollowRedirectsTestCase.java
src/test/java/org/mule/test/http/functional/requester/HttpRequestKeepAliveTestCase.java
src/test/java/org/mule/test/http/functional/requester/HttpRequestPartsTypeTestCase.java

including transitive dependencies from filter ones
* Cleanup test artifact dependencies so no unwanted transitive
dependencies en up in the APP classloader for tests

MULE-12327: ArtifactClassLoaderRunner - Application URLs are also

---

src/main/java/org/mule/extension/http/internal/listener/HttpListener.java
src/test/java/org/mule/test/http/functional/listener/HttpListenerErrorInterpretationTestCase.java

Application API
* ErrorTypeRepositry moved to mule-api

MULE-11706: Move Interceptor handlers registration from MuleContext to

---

src/main/java/org/mule/extension/http/internal/listener/HttpListenerProvider.java

Added the configuration name and the port to the error while starting the server so it can be easily identified

MULE-9669: added port to the error

---

src/test/java/org/mule/test/http/functional/requester/ocsp/AbstractHttpOcspRevocationTestCase.java

Correction of tests with OCSP REVOCATION and NO REVOCATION.
The main cause was found because Openssl is not installed by default in a Windows environment, it was tried to install Openssl for Windows but it did not work correctly; however, the setup() of these tests was omitted and the Openssl that was in the same Windows network was configured in another Unix machine and it was verified that the tests do not have any problem, the tests work well.
These tests will not run in the Windows environment.

MULE-15685: Fix HTTP connector tests in Windows

---

src/main/java/org/mule/extension/http/internal/listener/HttpListener.java

MULE-15871: Some HTTP log entries go to the runtime log instead of the

---

src/test/java/org/mule/test/http/functional/listener/HttpListenerErrorHandlingTestCase.java
src/test/resources/http-listener-error-handling-config.xml

on the OnError Flow Handlers
* Removing tests that make no sense. When interacting with the source for handling an error, it should not matter whether the error was produced inside an error handler or not, only if it happened in the flow.

MULE-16140: Source On Error callback is not called when an error occurs

---

pom.xml
src/main/java/org/mule/extension/http/api/HttpRequestAttributes.java
src/main/java/org/mule/extension/http/api/HttpRequestAttributesBuilder.java
src/main/java/org/mule/extension/http/api/HttpResponseAttributes.java
src/main/java/org/mule/extension/http/internal/request/builder/HttpResponseAttributesBuilder.java
src/test/munit/attributes/attributes-created-dw-test-case.xml

* Also, add support for MTF tests
Cherry pick for 1.5.x, had to cherrypick some changes in `HttpResponseAttributesBuilder ` also.

MULE-17848: Add builder methods for http attribute classes (#377)

---

src/main/java/org/mule/extension/http/api/policy/HttpListenerPolicyPointcutParameters.java
src/main/java/org/mule/extension/http/api/policy/HttpListenerPolicyPointcutParametersFactory.java
src/test/java/org/mule/test/http/policy/HttpListenerPolicyPointcutParametersFactoryTestCase.java

No `minMuleVersion` bump required with this implementation.

MULE-17985: Support policy application depending on request headers

---

src/main/java/org/mule/extension/http/api/policy/HttpListenerPolicyPointcutParameters.java
src/main/java/org/mule/extension/http/api/policy/HttpListenerPolicyPointcutParametersFactory.java
src/test/java/org/mule/test/http/policy/HttpListenerPolicyPointcutParametersFactoryTestCase.java

Reverts mulesoft/mule-http-connector#397
Reverting in master, this change will still be included in `2.0.x` branch

Revert "MULE-17985: Support policy application depending on request headers"

---

src/main/java/org/mule/extension/http/api/listener/HttpBasicAuthenticationFilter.java
src/main/java/org/mule/extension/http/internal/filter/BasicUnauthorisedException.java

`HttpBasicAuthenticationFilter#authenticate`
* Part 1: Token decoding
```
BasicAuthDecodeBenchmark.newWay                                      avgt   10   195.854 ±   2.988   ns/op
BasicAuthDecodeBenchmark.newWay:·gc.alloc.rate                       avgt   10  4448.987 ±  68.609  MB/sec
BasicAuthDecodeBenchmark.newWay:·gc.alloc.rate.norm                  avgt   10   320.000 ±   0.001    B/op
BasicAuthDecodeBenchmark.newWay:·gc.churn.PS_Eden_Space              avgt   10  4467.929 ±  70.765  MB/sec
BasicAuthDecodeBenchmark.newWay:·gc.churn.PS_Eden_Space.norm         avgt   10   321.365 ±   2.294    B/op
BasicAuthDecodeBenchmark.newWay:·gc.churn.PS_Survivor_Space          avgt   10     0.192 ±   0.016  MB/sec
BasicAuthDecodeBenchmark.newWay:·gc.churn.PS_Survivor_Space.norm     avgt   10 …
```

MULE-18039: Improve performance of

---

src/main/java/org/mule/extension/http/api/request/builder/HttpRequesterRequestBuilder.java
src/test/java/org/mule/test/http/functional/requester/HttpRequestUriParamsEncodingTestCase.java
src/test/java/org/mule/test/http/functional/requester/HttpRequestUriParamsTestCase.java
src/test/resources/http-request-uri-params-config.xml

MULE-18241: `mule.http.client.encodeUriParams` wrongly encodes spaces in

---

src/main/java/org/mule/extension/http/internal/request/HttpRequester.java
src/test/java/org/mule/extension/http/internal/request/HttpRequesterAuthConsumesPayloadTestCase.java

The condition that decided whether to make the body repeatable was not taking the possibility of no authentication into account.

MULE-18307: Using "payload" in an expression for refreshTokenWhen property results in an Error

---

src/main/java/org/mule/extension/http/internal/request/HttpRequestOperations.java
src/test/java/org/mule/test/http/functional/requester/HttpRequestPathTestCase.java
src/test/java/org/mule/test/http/functional/requester/HttpRequestPathsTestCase.java
src/test/java/org/mule/test/http/functional/requester/HttpRequestUriParamsTestCase.java
src/test/resources/http-request-path-reserved-encoded-config.xml

Clarification: I am adding the code to encode characters in the connector instead of the runtime, because: 
1. If we add it in the runtime (as where `encodeSpaces` is), we could add a new method (we would need a higher min mule version) or use `encodeSpaces`... which would be conceptually incorrect... 
2. So the change of behaviour depends entirely in the connector, rather than the runtime. 
If we have no problem of using `encodeSpaces` and having a different behaviour between mule versions, we could think of having the fix on runtime side (which would _look better_ since we are already depending on Guava and could use `ImmutableMap`)

MULE-19456: Encode characters from RFC 3986 in HTTP Request Path

---

src/test/java/org/mule/test/http/internal/listener/HttpListenerProviderTestCase.java

The HttpListenerBindTestCase system test was split up into two unit tests:
- One in [mule](https://github.com/mulesoft/mule/pull/11460) which tests that the exception thrown is logged with the correct classloader
- This one which tests that the exception is correctly wrapped as a MuleException
A test in http-service which checks that an exception is thrown if the port is already being used already [exists](https://github.com/mulesoft/mule-http-service/blob/master/src/test/java/org/mule/service/http/impl/functional/server/HttpServerBindTestCase.java)

W-11090837: Migrate HttpListenerBindTestCase to unit test

---

pom.xml
src/main/java/org/mule/extension/http/api/error/HttpError.java
src/test/java/org/mule/test/http/functional/requester/HttpRequestErrorHandlingTestCase.java
src/test/resources/http-request-errors-config.xml

Composer needs to identify the HTTP 301 error code returned when it tries to make a connection.

W-11139894 - HTTP Connector: added support for HTTP 3xx errors. It is required for HTTP Composer Connector in order to identify these kind of errors.

---

pom.xml

This fixes an issue where `mvn versions:set -DnewVersion=X.Y.Z` didn't update the extension's version, because it doesn't have the aggregator pom as parent

W-14728849: Add processAllModules to aggregator pom's versions-maven-plugin configuration

---

functional-tests/http/src/test/java/org/mule/test/http/functional/requester/HttpRequestUrlTestCase.java
functional-tests/http/src/test/resources/http-request-url-config.xml

**Summary**
- Added a new test case for a more complex case where there are multiple query params that are created differently
- Fixed the current tests by changing the query params type to LinkedHashMap to preserve the order (so we can assert)
**Related PRs**
https://github.com/mulesoft-labs/mule-http2-service/pull/7

W 14989170: Add new functional test case for Http Request with multiple query params

---

functional-tests/http/src/test/java/org/mule/test/http/HttpClientReflectionTestCase.java
mule-http-connector/src/main/java/org/mule/extension/http/internal/request/HttpClientReflection.java

This PR fixes two issues:
1. W-15043656: HttpClientReflection was creating only one static instance of HttpRequestOptionsBuilder. This caused an issue where the same options were mixed between different calls to sendAsync. The solution to this issue is constructing one builder per sendAsync call, and only caching the Method instances.
2. W-14989356: HttpClientReflection was handling all sendAsync exceptions in the same way: ignoring them and invoking the deprecated version of sendAsync. This caused an issue where the sendAsync was called twice when the first call was throwing a RuntimeException. The solution to this issue is handling each type of exception properly.

W-15043656: Use one request option builder per sendAsync invocation to avoid concurrency issues

---

functional-tests/http/src/test/java/org/mule/test/http/functional/listener/crl/HttpListenerCrlNoRevocationTestCase.java
functional-tests/http/src/test/java/org/mule/test/http/functional/listener/crl/HttpListenerCrlRevocationTestCase.java
functional-tests/http/src/test/java/org/mule/test/http/functional/listener/crl/HttpListenerRevocationOutdatedCrlTestCase.java
functional-tests/http/src/test/java/org/mule/test/http/functional/requester/crl/HttpPreferringCrlTestCase.java
functional-tests/http/src/test/java/org/mule/test/http/functional/requester/crl/HttpRequesterClrRevocationOutdatedCrlTestCase.java
functional-tests/http/src/test/java/org/mule/test/http/functional/requester/crl/HttpRequesterClrRevocationTestCase.java
functional-tests/http/src/test/java/org/mule/test/http/functional/requester/ocsp/HttpRequesterOcspRevocationTestCase.java

The code change [here](https://github.com/mulesoft/mule/pull/13527) is tested by the tests enabled by these changes
This effort is tracked as part of [W-14234781](https://gus.lightning.force.com/lightning/r/ADM_Work__c/a07EE00001bmsyAYAQ/view) .

W-15255505: Enabling TLS crl tests in HTTP Connector

---

functional-tests/pom.xml

when an SQLException is thrown an it cannot be serialised

W-16546951: Batch job scope not executing second batch step with Java 17
